#### GET request to example server
#GET https://examples.http-client.intellij.net/get
#    ?generated-in=IntelliJ IDEA

### 测试接口
GET http://localhost:8080/depts
Content-Type: application/json

###
GET http://localhost:8080/emps?page=1&pageSize=5
Content-Type: application/json

###
GET http://localhost:8080/emps?page=1&pageSize=5&name=阮&gender=1&begin=2010-01-01&end=2020-01-01
Accept: application/json

###
POST http://localhost:8080/emps
Content-Type: application/json

{
  "username": "zhangsan2",
  "name": "张三",
  "gender": 1,
  "phone": "18335753333",
  "job": 2,
  "salary": 8000,
  "image": "2.jpg",
  "entryDate": "2024-01-01",
  "deptId": 1,
  "exprList": [
    {
      "company": "百度",
      "job": "Java开发",
      "begin": "2000-01-01",
      "end": "2020-01-01"
    }
  ]
}

### 删除员工
DELETE http://localhost:8080/emps?ids=1,2,3

### 测试登录接口
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "zhangsan",
  "password": "123456"
}